import { SpaceItem, ServiceItem } from './types';

export const defaultSpaces: SpaceItem[] = [
  {
    id: 'sp-1',
    name: 'Imperial Hall (Indoor)',
    capacity: 350,
    price: 50000,
    description: 'Exclusive use of the main hall with central air conditioning, acoustic treatment...',
  },
  {
    id: 'sp-2',
    name: 'Palms Garden (Outdoor)',
    capacity: 200,
    price: 35000,
    description: 'Wooded outdoor area with hardwood pergola, altar, and walkway.',
  },
  {
    id: 'sp-3',
    name: 'Sunset Terrace & Lounge Bar',
    capacity: 120,
    price: 25000,
    description: 'Area with panoramic sunset view, modern cocktail bar, and lounge sofas.',
  },
];

export const defaultCatalogServices: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Imperial Hall Rental (Air Conditioned)',
    category: 'SPACE',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'FIXED',
    price: 50000,
    description: 'Exclusive use of the main hall with central air conditioning, acoustic treatment...',
  },
  {
    id: 'srv-2',
    name: 'Palms Garden Rental (Outdoor Ceremony)',
    category: 'SPACE',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'FIXED',
    price: 35000,
    description: 'Wooded outdoor area with hardwood pergola, altar, and walkway.',
  },
  {
    id: 'srv-3',
    name: 'Sunset Terrace & Lounge Bar Rental',
    category: 'SPACE',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'FIXED',
    price: 25000,
    description: 'Area with panoramic sunset view, modern cocktail bar, and lounge sofas.',
  },
  {
    id: 'srv-4',
    name: 'LED & Architectural Scenic Lighting',
    category: 'SPACE',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'FIXED',
    price: 18000,
    description: 'Lighting design with colored LED strip lights and spotlights for pillars and facades.',
  },
  {
    id: 'srv-5',
    name: '150 kVA Silent Power Generator',
    category: 'SPACE',
    providerType: 'EXTERNAL',
    providerName: 'VOLTA GENERATORS INC.',
    priceType: 'FIXED',
    price: 24000,
    description: 'Generator set with fuel and dedicated technician during 8h event.',
  },
  {
    id: 'srv-6',
    name: 'Royal Gold Banquet Buffet (Complete)',
    category: 'EVENT',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'PER_GUEST',
    price: 1200,
    description: 'Passed appetizers, 3-course plated dinner, gourmet desserts, and coffee.',
  },
  {
    id: 'srv-7',
    name: 'Premium Cocktail & Drinks Open Bar',
    category: 'EVENT',
    providerType: 'INTERNAL',
    providerName: 'Internal Venue',
    priceType: 'PER_GUEST',
    price: 300,
    description: 'Performative bartenders, imported spirits, caipirinhas, and gin & tonic.',
  },
  {
    id: 'srv-8',
    name: 'Noble Floral Decoration & Scenography',
    category: 'EVENT',
    providerType: 'EXTERNAL',
    providerName: 'FLORA DECOR LTD',
    priceType: 'FIXED',
    price: 65000,
    description: 'Arrangements with noble seasonal flowers, scenic cake table, and lounges.',
  },
];
